# Generated by Claude Code
"""
JIRA ticket key extraction and validation.

This module handles extraction of JIRA ticket keys from text
and validates ticket key formats.
"""

import re
from dataclasses import dataclass


class InvalidTicketKeyError(ValueError):
    """Raised when a JIRA ticket key is invalid."""

    pass


@dataclass
class JIRATicketKey:
    """
    Represents a validated JIRA ticket identifier.

    Attributes:
        raw_key: Original ticket key string (e.g., "JN-1234")
        project: Project prefix (e.g., "JN", "AIPCC")
        number: Ticket number
    """

    raw_key: str

    def __post_init__(self):
        """Validate and parse ticket key after initialization."""
        # Validate format: [A-Z]+-\d+
        if not re.match(r"^[A-Z]+-\d+$", self.raw_key):
            raise InvalidTicketKeyError(
                f"Invalid JIRA ticket key format: {self.raw_key}\n"
                f"Expected format: PROJECT-NUMBER (e.g., JN-1234, AIPCC-7354)"
            )

        # Parse components
        parts = self.raw_key.split("-")
        self.project = parts[0]
        self.number = int(parts[1])


def extract_ticket_from_text(text: str) -> JIRATicketKey | None:
    r"""
    Extract JIRA ticket key from text.

    Searches for first occurrence of pattern [A-Z]+-\d+ in text.

    Args:
        text: Text to search for ticket key

    Returns:
        JIRATicketKey if found, None otherwise

    Example:
        >>> extract_ticket_from_text("Let's discuss JN-1234 implementation")
        JIRATicketKey(raw_key='JN-1234', project='JN', number=1234)
        >>> extract_ticket_from_text("No ticket here")
        None
    """
    # Pattern: [A-Z]+-\d+ (e.g., JN-1234, PROJ-567)
    # Matches JIRA ticket format: uppercase letters, hyphen, numbers
    pattern = r"[A-Z]+-\d+"
    match = re.search(pattern, text)

    if not match:
        return None

    ticket_key = match.group(0)
    return JIRATicketKey(raw_key=ticket_key)
